name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package:
        description: Package name
        default: visual-storyboard
      version:
        description: Package version
        default: 0.3.6

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v4

      - name: Publish doc
        id: publish-doc
        uses: ./.github/actions/publish-doc
        with:
          package: ${{ inputs.package || 'visual-storyboard' }}
          version: ${{ inputs.version || '0.3.6' }}
          rclone-secret-access-key: ${{ secrets.RCLONE_CONFIG_PUBLISH_SECRET_ACCESS_KEY }}
          grist-api-key: ${{ secrets.GRIST_API_KEY }}

      - name: Summary
        run: echo "[${{ steps.publish-doc.outputs.url }}](${{ steps.publish-doc.outputs.url }})" >> $GITHUB_STEP_SUMMARY
