name: Publish

on:
  push:
    branches:
      - main

env:
  PACKAGE_NAME: visual-storyboard
  PACKAGE_VERSION: 0.3.6

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create dist and tmp directories
        run: mkdir -p dist tmp && chmod 777 dist tmp

      - name: Run publish
        run: |
          docker run \
            -e RCLONE_CONFIG_PUBLISH_TYPE=local \
            -e APIREF_STORAGE_BUCKET=publish:/dist \
            -e TMPDIR=/workspace/tmp \
            --rm \
            -v $PWD/dist:/dist \
            -v $PWD/tmp:/workspace/tmp \
            ghcr.io/dtinth/apiref:develop \
            publish "$PACKAGE_NAME@$PACKAGE_VERSION"

      - name: Upload dist artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist

      - name: Fix tmp directory permissions
        if: always()
        run: sudo chown -R $(id -u):$(id -g) tmp

      - name: Upload tmp artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: tmp
          path: tmp
          if-no-files-found: ignore
